#!/bin/sh
. /etc/wb_env.sh

CONFFILE=/etc/wb-mqtt-smartweb.conf
DEFAULT=/etc/wb-mqtt-smartweb.conf.sample

ucf --debconf-ok $DEFAULT $CONFFILE


if [ -x "/etc/init.d/wb-mqtt-smartweb" ] || [ -e "/etc/init/wb-mqtt-smartweb.conf" ]; then
	if [ ! -e "/etc/init/wb-mqtt-smartweb.conf" ]; then
		update-rc.d wb-mqtt-smartweb defaults >/dev/null
	fi
	invoke-rc.d wb-mqtt-smartweb start || true
fi

exit 0
# ignore debhelper

#DEBHELPER#
